# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: youth_read

on:
  workflow_dispatch:
  schedule:
     - cron: '1 6-14/2 * * *'
  watch:
    types: started
jobs:
  build:
    env:
      YOUTH_READ4: ${{ secrets.YOUTH_READ4 }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【中青看点-文章阅读4-测试篇】'
        if: env.YOUTH_READ4
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ4 }}          
      - name: '运行 【中青看点-文章阅读-54篇】'
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ }}

      - name: '运行 【中青看点-文章阅读2-54篇】'
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ2 }}
      - name: '运行 【中青看点-文章阅读3-35篇】'
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ3 }}
